config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

name: 'sap_source'
version: '0.1.0'

models:
  sap_source:
    +materialized: table
    +schema: stg_sap


vars:
  sap_source:
    bkpf: "{{ source('sap','bkpf') }}"
    bseg: "{{ source('sap','bseg') }}"
    faglflexa: "{{ source('sap','faglflexa') }}"
    faglflext: "{{ source('sap','faglflext') }}"
    mara: "{{ source('sap','mara') }}"
    ska1: "{{ source('sap','ska1') }}"
    t001: "{{ source('sap','t001') }}"

clean-targets:
  - target
  - dbt_modules
  - dbt_packages