config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

name: 'sap_source'
version: '0.1.0'

models:
  sap_source:
    +materialized: table
    +schema: stg_sap


vars:
  sap_source:

clean-targets:
  - target
  - dbt_modules
  - dbt_packages
