name: 'sap_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  sap_schema: sap_source_integration_tests
  sap_source:
    sap_bkpf_identifier: "sap_bkpf_data"
    sap_bseg_identifier: "sap_bseg_data"
    sap_faglflexa_identifier: "sap_faglflexa_data"
    sap_faglflext_identifier: "sap_faglflext_data"
    sap_mara_identifier: "sap_mara_data"
    sap_ska1_identifier: "sap_ska1_data"
    sap_t001_identifier: "sap_t001_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  sap_source_integration_tests:
    +column_types:
      _fivetran_rowid: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
      _fivetran_synced: timestamp
    sap_bkpf_data:
      +column_types:
        aedat: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        awkey: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        belnr: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        bldat: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        budat: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        cpudt: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        cputm: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        reindat: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        stodt: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        upddt: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        wwert: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
    sap_faglflexa_data:
      +column_types:
        belnr: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        budat: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        docln: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        docnr: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        racct: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        timestamp: numeric
    sap_faglflext_data:
      +column_types:
        belnr: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        budat: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        docln: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        docnr: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        racct: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        timestamp: numeric

# Seed Data

