name: 'sap_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  sap_source:
    sap_schema: sap_source_integration_tests

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']


    # Seed Data

